### PR TITLE
multiple AS topology parsed from multiple rocketfuel

### PR DESCRIPTION
**Pull request by zpymyyn**
Parsed multiple rocketfuel topology files.
Taking each as an AS.
source-router link across ASes are set with external delay.

### CODE REVIEW

**Comment by zpymyyn** [comment]
fix the error

**Comment by lorenzosaino** [comment]
@zpymyyn thanks a lot for the pull request. I will review it as soon as possible and let you know.

**Comment by zpymyyn** [comment]
a bug found with icr candidates, should change to
862       topo_multiAS.graph['icr_candidates']=topo_multiAS.graph['icr_candidates'].union(set(routerslistsort[j]))

with definition before the loop
topo_multiAS.graph['icr_candidates'] = set()

Thanks

**Comment by zpymyyn** [comment]
I've been doing simulation while testing the topo.
Found some bugs and now fixed. 
But I don't have much time recently to make it prettier and have to leave it ugly as it is now.
Here is the link if you are interested, please feel free.
https://github.com/zpymyyn/icarus/blob/ICNbroker/icarus/scenarios/topology.py

**Comment by lorenzosaino** [comment]
Sorry for the late reply.

So, if I understood correctly the code in this pull request has known bugs that you fixed in your own fork but the code in your fork still needs work to be merged. Am I correct?

I am sorry but I cannot merge code that has known bugs because that'll affect other users that may incur into this bugs. So, I am not going to merge this pull request for now.

If you plan on doing more work on your fork to the point of making it clean enough for merging, feel free to either update this pull request or open a new one and I will be happy to review it and merge it.

Thanks!

**Comment by zpymyyn** [comment]
Hi,

Yes, that’s correct.

I will update it once make it better with more scalability and robust.

Thanks.
Pengyuan

**Comment by lorenzosaino** [comment]
Since there was no recent activity, I am closing this for now.

**Pull request closed without merging**
